#Open webpages firefox
protocol http
action launch --type=background firefox ${URL}

protocol https
action launch --type=background firefox ${URL}

# Open browser-friendly local files in Firefox or the default browser
protocol file
ext html,htm,xhtml,svg,pdf
action launch --type=background xdg-open ${FILE_PATH}

# Open text files in your editor
protocol file
mime text/*
action launch --type=overlay --cwd=current ${EDITOR} -- ${FILE_PATH}

# Open images inside kitty
protocol file
mime image/*
action launch --type=overlay kitten icat --hold -- ${FILE_PATH}

# Open shell scripts with confirmation
protocol file
ext sh,bash,zsh,fish,command,tool
action launch --hold --type=os-window kitten __shebang__ confirm-always ${FILE_PATH} ${SHELL}

# Open directories in a new kitty window
protocol file
mime inode/directory
action launch --type=os-window --cwd -- ${FILE_PATH}

# Ask before running executables
protocol file
mime inode/executable,application/vnd.microsoft.portable-executable
action launch --hold --type=os-window kitten __confirm_and_run_exe__ ${FILE_PATH}

# Fallback: open anything else with the system opener
protocol file
action launch --type=background xdg-open ${FILE_PATH}
